# Generated by Django 3.2.19 on 2026-09-19 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reserved_seats',
            field=models.TextField(blank=True, null=True),
        ),
    ]
