# Generated by Django 3.2.19 on 2026-09-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_payment_reserved_seats'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booked_at'], name='movies_book_booked__a7ab7e_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['theater', 'booked_at'], name='movies_book_theater_a2fd03_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['movie', 'booked_at'], name='movies_book_movie_i_323598_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='movies_paym_created_5e9beb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='movies_paym_status_5316c9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='movies_paym_status_8acdf7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['theater', 'created_at'], name='movies_paym_theater_0633d7_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['theater'], name='movies_seat_theater_5b3dc4_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['theater', 'is_booked'], name='movies_seat_theater_7e5f1d_idx'),
        ),
        migrations.AddIndex(
            model_name='seat',
            index=models.Index(fields=['theater', 'is_reserved'], name='movies_seat_theater_8f80d5_idx'),
        ),
    ]
