# Generated by Django 3.2.19 on 2026-09-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20260927_1433'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='booking',
            name='movies_book_booked__a7ab7e_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='movies_paym_created_5e9beb_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='movies_paym_status_5316c9_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='movies_paym_theater_0633d7_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=20),
        ),
    ]
