# Generated by Django 3.2.19 on 2026-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
