# Generated by Django 3.2.19 on 2026-09-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20260930_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='city',
            field=models.CharField(default='Ahmedabad', max_length=100),
            preserve_default=False,
        ),
    ]
