# Generated by Django 3.2.19 on 2026-10-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_alter_theater_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket',
            field=models.FileField(blank=True, null=True, upload_to='tickets/'),
        ),
        migrations.AddField(
            model_name='theater',
            name='screen',
            field=models.CharField(default='Screen 1', max_length=100),
        ),
    ]
